### ISSUE TITLE
ps0271-ntdll-Implement-dynamic-spinning.mypatch Can't be applied on latest TKG 

### ISSUE THREAD

**Issue by llde** [openglfreak/wine-tkg-userpatches#3]
Applying your own patch ps0271-ntdll-Implement-dynamic-spinning.mypatch
patching file dlls/ntdll/sync.c
Hunk #1 FAILED at 34.
Hunk #2 FAILED at 159.
Hunk #3 FAILED at 189.
Hunk #4 FAILED at 403.
4 out of 4 hunks FAILED -- saving rejects to file dlls/ntdll/sync.c.rej

Last wine-tkg-git  (staging version) fail with this error.

**Comment by openglfreak** [comment]
If you're cherry-picking just that one patch, you need to rebase it onto staging.
With the included config, all the patches before that one, and wine/-tkg version from the latest commit, it should work.

**Comment by llde** [comment]
ok thanks (yes I'm cherry picking some patches)
