### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by gel-crabs** [openglfreak/wine-tkg-userpatches#4]
There's no documentation. Do I clone it into the wine-tkg-userpatches directory? Do I move certain files to different directories?

**Comment by pongo1231** [comment]
Simply clone the repo and link the `_EXT_CONFIG_PATH` entry (located in `wine-tkg-profiles/advanced-customization.cfg`) to the `wine-tkg.cfg`.

**Comment by gel-crabs** [comment]
Thank you!

**Comment by Nolij** [comment]
Could this be added in a README?
